class X12_835_5010_X221A1_Heading_1000B_REF_V0 {   
    REF01_reference_identification_qualifier string
    REF02_reference_identification string?
    REF03_description string?
    REF04_composite_reference_identifier X12_835_5010_X221A1_Heading_1000B_REF_C040_V0?
}

class X12_835_5010_X221A1_Heading_1000B_REF_C040_V0 {
    C040_01_reference_identification_qualifier string
    C040_02_reference_identification string
    C040_03_reference_identification_qualifier string?
    C040_04_reference_identification string?
    C040_05_reference_identification_qualifier string?
    C040_06_reference_identification string?
}
