###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class X12Input(BaseModel):
    release: Literal[5010]
    transaction_set_id: Literal[835]
    data: Optional[str] = None

class X12Output(BaseModel):
    release: Optional[int] = None
    transaction_set_id: Optional[int] = None
    data: Optional["X12_835_5010"] = None

class X12_835_5010(BaseModel):
    ISA_interchange_control_header: Optional["X12_835_5010_ISA_V0"] = None
    IEA_interchange_control_trailer: Optional["X12_835_5010_IEA_V0"] = None
    ST_transaction_set_header: Optional["X12_835_5010_ST_V0"] = None
    BPR_financial_information: Optional["X12_835_5010_BPR_V0"] = None
    TRN_reassociation_trace_number: Optional["X12_835_5010_TRN_V0"] = None
    CUR_foreign_currency_information: Optional["X12_835_5010_CUR_V0"] = None
    REF_receiver_identification: Optional["X12_835_5010_REF_V0"] = None
    DTM_production_date: Optional["X12_835_5010_DTM_V0"] = None
    N1_entity_information: List["X12_835_5010_N1_V0"]
    N2_additional_name_information: List["X12_835_5010_N2_V0"]
    N3_address_information: List["X12_835_5010_N3_V0"]
    N4_geographic_location: List["X12_835_5010_N4_V0"]
    LX_service_line_number: List["X12_835_5010_LX_V0"]
    CLP_claim_payment_information: List["X12_835_5010_CLP_V0"]
    NM1_individual_or_organizational_name: List["X12_835_5010_NM1_V0"]
    MOA_monetary_amount: List["X12_835_5010_MOA_V0"]
    SVC_service_payment_information: List["X12_835_5010_SVC_V0"]
    CAS_claim_adjustment: List["X12_835_5010_CAS_V0"]
    AMT_monetary_amount: List["X12_835_5010_AMT_V0"]

class X12_835_5010_AMT_V0(BaseModel):
    AMT01_amount_qualifier_code: Optional[str] = None
    AMT02_monetary_amount: Optional[str] = None
    AMT03_credit_debit_flag_code: Optional[str] = None

class X12_835_5010_BPR_V0(BaseModel):
    BPR01_transaction_handling_code: Optional[str] = None
    BPR02_monetary_amount: Optional[float] = None
    BPR03_credit_debit_flag_code: Optional[str] = None
    BPR04_payment_method_code: Optional[str] = None
    BPR05_payment_format_code: Optional[str] = None
    BPR06_depository_financial_institution_dfi_identification_number_qualifier: Optional[str] = None
    BPR07_sender_dfi_identifier: Optional[str] = None
    BPR08_account_number_qualifier: Optional[str] = None
    BPR09_sender_bank_account_number_09: Optional[str] = None
    BPR10_payer_identifier: Optional[str] = None
    BPR11_originating_company_supplemental_code: Optional[str] = None
    BPR12_originating_company_payment_type_code: Optional[str] = None
    BPR13_originating_company_payment_type_code: Optional[str] = None
    BPR14_originating_company_payment_type_code: Optional[str] = None
    BPR15_originating_company_payment_type_code: Optional[str] = None
    BPR16_originating_company_payment_type_code: Optional[str] = None
    BPR17_originating_company_payment_type_code: Optional[str] = None
    BPR18_originating_company_payment_type_code: Optional[str] = None
    BPR19_originating_company_payment_type_code: Optional[str] = None
    BPR20_payment_date: Optional[str] = None

class X12_835_5010_CAS_V0(BaseModel):
    CAS01_adjustment_group_code: Optional[str] = None
    CAS02_adjustment_reason_code: Optional[str] = None
    CAS03_adjustment_amount: Optional[str] = None
    CAS04_quantity: Optional[str] = None
    CAS05_additional_reason_code: Optional[str] = None
    CAS06_additional_adjustment_amount: Optional[str] = None

class X12_835_5010_CLP_V0(BaseModel):
    CLP01_patient_control_number: Optional[str] = None
    CLP02_claim_status_code: Optional[str] = None
    CLP03_total_claim_charge_amount: Optional[str] = None
    CLP04_total_claim_payment_amount: Optional[str] = None
    CLP05_patient_responsibility_amount: Optional[str] = None
    CLP06_total_claim_disallowed_amount: Optional[str] = None
    CLP07_claim_identifier: Optional[str] = None
    CLP08_provider_adjustment_amount: Optional[str] = None
    CLP09_claim_frequency_code: Optional[str] = None

class X12_835_5010_CUR_V0(BaseModel):
    CUR01_entity_identifier_code: Optional[str] = None
    CUR02_currency_code: Optional[str] = None
    CUR03_exchange_rate: Optional[str] = None
    CUR04_currency_conversion_type_code: Optional[str] = None
    CUR05_currency_unit_or_basis: Optional[str] = None

class X12_835_5010_DTM_V0(BaseModel):
    DTM01_date_time_qualifier: Optional[str] = None
    DTM02_date: Optional[str] = None
    DTM03_time: Optional[str] = None

class X12_835_5010_GE_V0(BaseModel):
    GE01_number_of_transaction_sets_included: Optional[str] = None
    GE02_group_control_number: Optional[str] = None

class X12_835_5010_GS_V0(BaseModel):
    GS01_functional_identifier_code: Optional[str] = None
    GS02_application_sender_code: Optional[str] = None
    GS03_application_receiver_code: Optional[str] = None
    GS04_date: Optional[str] = None
    GS05_time: Optional[str] = None
    GS06_group_control_number: Optional[str] = None
    GS07_responsible_agency_code: Optional[str] = None
    GS08_version_release_code: Optional[str] = None

class X12_835_5010_IEA_V0(BaseModel):
    IEA01_number_of_functional_groups_included: Optional[str] = None
    IEA02_interchange_control_number: Optional[str] = None

class X12_835_5010_ISA_V0(BaseModel):
    ISA01_authorization_information_qualifier: Optional[str] = None
    ISA02_authorization_information: Optional[str] = None
    ISA03_security_information_qualifier: Optional[str] = None
    ISA04_security_information: Optional[str] = None
    ISA05_interchange_id_qualifier_sender: Optional[str] = None
    ISA06_interchange_sender_id: Optional[str] = None
    ISA07_interchange_id_qualifier_receiver: Optional[str] = None
    ISA08_interchange_receiver_id: Optional[str] = None
    ISA09_interchange_date: Optional[str] = None
    ISA10_interchange_time: Optional[str] = None
    ISA11_repetition_separator: Optional[str] = None
    ISA12_interchange_control_version_number: Optional[str] = None
    ISA13_interchange_control_number: Optional[str] = None
    ISA14_acknowledgment_requested: Optional[str] = None
    ISA15_usage_indicator: Optional[str] = None
    ISA16_component_element_separator: Optional[str] = None

class X12_835_5010_LX_V0(BaseModel):
    LX01_assigned_number: Optional[str] = None

class X12_835_5010_MOA_V0(BaseModel):
    MOA01_monetary_amount_qualifier_code: Optional[str] = None
    MOA02_monetary_amount: Optional[str] = None
    MOA03_reference_identification: Optional[str] = None

class X12_835_5010_N1_V0(BaseModel):
    N101_entity_identifier_code: Optional[str] = None
    N102_name: Optional[str] = None
    N103_identification_code_qualifier: Optional[str] = None
    N104_identification_code: Optional[str] = None

class X12_835_5010_N2_V0(BaseModel):
    N201_name: Optional[str] = None
    N202_name: Optional[str] = None

class X12_835_5010_N3_V0(BaseModel):
    N301_address_information: Optional[str] = None
    N302_address_information: Optional[str] = None

class X12_835_5010_N4_V0(BaseModel):
    N401_city_name: Optional[str] = None
    N402_state_or_province_code: Optional[str] = None
    N403_postal_code: Optional[str] = None
    N404_country_code: Optional[str] = None
    N405_location_qualifier: Optional[str] = None
    N406_location_identifier: Optional[str] = None

class X12_835_5010_NM1_V0(BaseModel):
    NM101_entity_identifier_code: Optional[str] = None
    NM102_entity_type_qualifier: Optional[str] = None
    NM103_last_name_or_organization_name: Optional[str] = None
    NM104_first_name: Optional[str] = None
    NM105_middle_initial: Optional[str] = None
    NM106_name_prefix: Optional[str] = None
    NM107_name_suffix: Optional[str] = None
    NM108_identification_code_qualifier: Optional[str] = None
    NM109_identification_code: Optional[str] = None

class X12_835_5010_PER_V0(BaseModel):
    PER01_contact_function_code: Optional[str] = None
    PER02_contact_name: Optional[str] = None
    PER03_communication_number_qualifier: Optional[str] = None
    PER04_communication_number: Optional[str] = None
    PER05_communication_number_qualifier: Optional[str] = None
    PER06_communication_number: Optional[str] = None

class X12_835_5010_REF_V0(BaseModel):
    REF01_reference_identification_qualifier: Optional[str] = None
    REF02_reference_identification: Optional[str] = None
    REF03_description: Optional[str] = None

class X12_835_5010_SE_V0(BaseModel):
    SE01_segment_count: Optional[str] = None
    SE02_transaction_set_control_number: Optional[str] = None

class X12_835_5010_ST_V0(BaseModel):
    ST01_transaction_set_identifier_code: Optional[str] = None
    ST02_transaction_set_control_number: Optional[str] = None

class X12_835_5010_SVC_V0(BaseModel):
    SVC01_composite_medical_procedure_identifier: Optional[str] = None
    SVC02_line_item_charge_amount: Optional[str] = None
    SVC03_line_item_payment_amount: Optional[str] = None
    SVC04_service_quantity: Optional[str] = None
    SVC05_composite_medical_procedure_identifier: Optional[str] = None

class X12_835_5010_TRN_V0(BaseModel):
    TNR01_trace_type_code: Optional[str] = None
    TNR03_check_or_eft_trace_number: Optional[str] = None
    TNR03_payer_identifier: Optional[str] = None
    TRN04_originating_company_supplemental_code: Optional[str] = None
