###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class X12_835_5010_X221A1_Detail_2100_2110_AMT_V0(BaseModel):
    AMT01_amount_qualifier_code: Optional[str] = None
    AMT02_monetary_amount: Optional[float] = None
    AMT03_credit_debit_flag_code: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_2110_CAS_V0(BaseModel):
    CAS01_claim_adjustment_group_code: Optional[str] = None
    CAS02_claim_adjustment_reason_code: Optional[str] = None
    CAS03_monetary_amount: Optional[float] = None
    CAS04_quantity: Optional[float] = None
    CAS05_claim_adjustment_reason_code: Optional[str] = None
    CAS06_monetary_amount: Optional[float] = None
    CAS07_quantity: Optional[float] = None
    CAS08_claim_adjustment_reason_code: Optional[str] = None
    CAS09_monetary_amount: Optional[float] = None
    CAS10_quantity: Optional[float] = None
    CAS11_claim_adjustment_reason_code: Optional[str] = None
    CAS12_monetary_amount: Optional[float] = None
    CAS13_quantity: Optional[float] = None
    CAS14_claim_adjustment_reason_code: Optional[str] = None
    CAS15_monetary_amount: Optional[float] = None
    CAS16_quantity: Optional[float] = None
    CAS17_claim_adjustment_reason_code: Optional[str] = None
    CAS18_monetary_amount: Optional[float] = None
    CAS19_quantity: Optional[float] = None

class X12_835_5010_X221A1_Detail_2100_2110_DTM_V0(BaseModel):
    DTM01_date_time_qualifier: Optional[str] = None
    DTM02_date: Optional[str] = None
    DTM03_time: Optional[str] = None
    DTM04_time_code: Optional[str] = None
    DTM05_date_time_period_format_qualifier: Optional[str] = None
    DTM06_date_time_period: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_2110_LQ_V0(BaseModel):
    LQ01_code_list_qualifier_code: Optional[str] = None
    LQ02_industry_code: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_2110_Loop_V0(BaseModel):
    SVC_service_payment_information: Optional["X12_835_5010_X221A1_Detail_2100_2110_SVC_V0"] = None
    DTM_service_date: List["X12_835_5010_X221A1_Detail_2100_2110_DTM_V0"]
    CAS_service_adjustment: List["X12_835_5010_X221A1_Detail_2100_2110_CAS_V0"]
    REF_service_identification: List["X12_835_5010_X221A1_Detail_2100_2110_REF_V0"]
    REF_line_item_control_number: Optional["X12_835_5010_X221A1_Detail_2100_2110_REF_V0"] = None
    REF_rendering_provider_information: List["X12_835_5010_X221A1_Detail_2100_2110_REF_V0"]
    REF_healthcare_policy_identification: List["X12_835_5010_X221A1_Detail_2100_2110_REF_V0"]
    AMT_service_supplemental_amount: List["X12_835_5010_X221A1_Detail_2100_2110_AMT_V0"]
    QTY_service_supplemental_quantity: List["X12_835_5010_X221A1_Detail_2100_2110_QTY_V0"]
    LQ_healthcare_remark_codes: List["X12_835_5010_X221A1_Detail_2100_2110_LQ_V0"]

class X12_835_5010_X221A1_Detail_2100_2110_QTY_C001_V0(BaseModel):
    C001_01_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_02_exponent: Optional[float] = None
    C001_03_multiplier: Optional[float] = None
    C001_04_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_05_exponent: Optional[float] = None
    C001_06_multiplier: Optional[float] = None
    C001_07_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_08_exponent: Optional[float] = None
    C001_09_multiplier: Optional[float] = None
    C001_10_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_11_exponent: Optional[float] = None
    C001_12_multiplier: Optional[float] = None
    C001_13_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_14_exponent: Optional[float] = None
    C001_15_multiplier: Optional[float] = None

class X12_835_5010_X221A1_Detail_2100_2110_QTY_V0(BaseModel):
    QTY01_quantity_qualifier: Optional[str] = None
    QTY02_quantity: Optional[float] = None
    QTY03_composite_unit_of_measure: Optional["X12_835_5010_X221A1_Detail_2100_2110_QTY_C001_V0"] = None
    QTY04_free_form_information: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_2110_REF_C040_V0(BaseModel):
    C040_01_reference_identification_qualifier: Optional[str] = None
    C040_02_reference_identification: Optional[str] = None
    C040_03_reference_identification_qualifier: Optional[str] = None
    C040_04_reference_identification: Optional[str] = None
    C040_05_reference_identification_qualifier: Optional[str] = None
    C040_06_reference_identification: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_2110_REF_V0(BaseModel):
    REF01_reference_identification_qualifier: Optional[str] = None
    REF02_reference_identification: Optional[str] = None
    REF03_description: Optional[str] = None
    REF04_composite_reference_identifier: Optional["X12_835_5010_X221A1_Detail_2100_2110_REF_C040_V0"] = None

class X12_835_5010_X221A1_Detail_2100_2110_SVC_C003_V0(BaseModel):
    C003_01_product_service_id_qualifier: Optional[str] = None
    C003_02_product_service_id: Optional[str] = None
    C003_03_procedure_modifier: Optional[str] = None
    C003_04_procedure_modifier: Optional[str] = None
    C003_05_procedure_modifier: Optional[str] = None
    C003_06_procedure_modifier: Optional[str] = None
    C003_07_description: Optional[str] = None
    C003_08_product_service_id: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_2110_SVC_V0(BaseModel):
    SVC01_composite_medical_procedure_identifier: Optional["X12_835_5010_X221A1_Detail_2100_2110_SVC_C003_V0"] = None
    SVC02_submitted_service_charge: Optional[float] = None
    SVC03_paid_service_amount: Optional[float] = None
    SVC04_revenue_code: Optional[str] = None
    SVC05_paid_units_of_service: Optional[float] = None
    SVC06_composite_medical_procedure_identifier: Optional["X12_835_5010_X221A1_Detail_2100_2110_SVC_C003_V0"] = None
    SVC07_original_submitted_units_of_service: Optional[float] = None

class X12_835_5010_X221A1_Detail_2100_AMT_V0(BaseModel):
    AMT01_amount_qualifier_code: Optional[str] = None
    AMT02_monetary_amount: Optional[float] = None
    AMT03_credit_debit_flag_code: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_CAS_V0(BaseModel):
    CAS01_claim_adjustment_group_code: Optional[str] = None
    CAS02_reason_code: Optional[str] = None
    CAS03_adjustment_amount: Optional[float] = None
    CAS04_adjustment_quantity: Optional[float] = None
    CAS05_reason_code: Optional[str] = None
    CAS06_adjustment_amount: Optional[float] = None
    CAS07_adjustment_quantity: Optional[float] = None
    CAS08_reason_code: Optional[str] = None
    CAS09_adjustment_amount: Optional[float] = None
    CAS10_adjustment_quantity: Optional[float] = None
    CAS11_reason_code: Optional[str] = None
    CAS12_adjustment_amount: Optional[float] = None
    CAS13_adjustment_quantity: Optional[float] = None
    CAS14_reason_code: Optional[str] = None
    CAS15_adjustment_amount: Optional[float] = None
    CAS16_adjustment_quantity: Optional[float] = None
    CAS17_reason_code: Optional[str] = None
    CAS18_adjustment_amount: Optional[float] = None
    CAS19_adjustment_quantity: Optional[float] = None

class X12_835_5010_X221A1_Detail_2100_CLP_V0(BaseModel):
    CLP01_claim_submitters_identifier: Optional[str] = None
    CLP02_claim_status_code: Optional[str] = None
    CLP03_submitted_charges_amount: Optional[float] = None
    CLP04_paid_amount: Optional[float] = None
    CLP05_patient_responsibility_amount: Optional[float] = None
    CLP06_claim_filing_indicator_code: Optional[str] = None
    CLP07_payer_control_number: Optional[str] = None
    CLP08_facility_code_value: Optional[str] = None
    CLP09_claim_frequency_type_code: Optional[str] = None
    CLP10_patient_status_code: Optional[str] = None
    CLP11_drg_code: Optional[str] = None
    CLP12_drg_weight: Optional[float] = None
    CLP13_discharge_fraction: Optional[float] = None
    CLP14_patient_authorization_to_coordinate_benefits: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_DTM_V0(BaseModel):
    DTM01_date_time_qualifier: Optional[str] = None
    DTM02_date: Optional[str] = None
    DTM03_time: Optional[str] = None
    DTM04_time_code: Optional[str] = None
    DTM05_date_time_period_format_qualifier: Optional[str] = None
    DTM06_date_time_period: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_Loop_V0(BaseModel):
    CLP_claim_payment_information: Optional["X12_835_5010_X221A1_Detail_2100_CLP_V0"] = None
    CAS_claim_adjustments: List["X12_835_5010_X221A1_Detail_2100_CAS_V0"]
    NM1_patient_name: Optional["X12_835_5010_X221A1_Detail_2100_NM1_V0"] = None
    NM1_insured_name: Optional["X12_835_5010_X221A1_Detail_2100_NM1_V0"] = None
    NM1_corrected_patient_or_insured_name: Optional["X12_835_5010_X221A1_Detail_2100_NM1_V0"] = None
    NM1_service_provider_name: Optional["X12_835_5010_X221A1_Detail_2100_NM1_V0"] = None
    NM1_crossover_carrier_name: Optional["X12_835_5010_X221A1_Detail_2100_NM1_V0"] = None
    NM1_corrected_priority_payer_name: Optional["X12_835_5010_X221A1_Detail_2100_NM1_V0"] = None
    NM1_other_subscriber_name: Optional["X12_835_5010_X221A1_Detail_2100_NM1_V0"] = None
    MIA_inpatient_adjudication_information: Optional["X12_835_5010_X221A1_Detail_2100_MIA_V0"] = None
    MOA_outpatient_adjudication_information: Optional["X12_835_5010_X221A1_Detail_2100_MOA_V0"] = None
    REF_other_claim_related_identification: List["X12_835_5010_X221A1_Detail_2100_REF_V0"]
    REF_rendering_provider_identification: List["X12_835_5010_X221A1_Detail_2100_REF_V0"]
    DTM_statement_from_to_date: List["X12_835_5010_X221A1_Detail_2100_DTM_V0"]
    DTM_coverage_expiration_date: Optional["X12_835_5010_X221A1_Detail_2100_DTM_V0"] = None
    DTM_claim_received_date: Optional["X12_835_5010_X221A1_Detail_2100_DTM_V0"] = None
    PER_claim_contact_information: List["X12_835_5010_X221A1_Detail_2100_PER_V0"]
    AMT_claim_supplemental_information: List["X12_835_5010_X221A1_Detail_2100_AMT_V0"]
    QTY_claim_supplemental_information_quantity: List["X12_835_5010_X221A1_Detail_2100_QTY_V0"]
    service_line_loop: List["X12_835_5010_X221A1_Detail_2100_2110_Loop_V0"]

class X12_835_5010_X221A1_Detail_2100_MIA_V0(BaseModel):
    MIA01_covered_days: Optional[float] = None
    MIA02_pps_operating_outlier_amount: Optional[float] = None
    MIA03_lifetime_psychiatric_days: Optional[float] = None
    MIA04_drg_amount: Optional[float] = None
    MIA05_claim_payment_remark_code: Optional[str] = None
    MIA06_disproportionate_share_amount: Optional[float] = None
    MIA07_msp_pass_through_amount: Optional[float] = None
    MIA08_total_pps_capital_amount: Optional[float] = None
    MIA09_pps_capital_federal_specific_drg_amount: Optional[float] = None
    MIA10_pps_capital_hospital_specific_drg_amount: Optional[float] = None
    MIA11_pps_capital_disproportionate_share_drg_amount: Optional[float] = None
    MIA12_old_capital_amount: Optional[float] = None
    MIA13_pps_capital_indirect_medical_education_claim_amount: Optional[float] = None
    MIA14_hospital_specific_drg_amount: Optional[float] = None
    MIA15_cost_report_days: Optional[float] = None
    MIA16_federal_specific_drg_amount: Optional[float] = None
    MIA17_pps_capital_outlier_amount: Optional[float] = None
    MIA18_indirect_teaching_amount: Optional[float] = None
    MIA19_professional_component_amount_billed_but_not_payable: Optional[float] = None
    MIA20_claim_payment_remark_code_1: Optional[str] = None
    MIA21_claim_payment_remark_code_2: Optional[str] = None
    MIA22_claim_payment_remark_code_3: Optional[str] = None
    MIA23_claim_payment_remark_code_4: Optional[str] = None
    MIA24_capital_exception_amount: Optional[float] = None

class X12_835_5010_X221A1_Detail_2100_MOA_V0(BaseModel):
    MOA01_reimbursement_rate: Optional[float] = None
    MOA02_hcpcs_payable_amount: Optional[float] = None
    MOA03_claim_payment_remark_code_1: Optional[str] = None
    MOA04_claim_payment_remark_code_2: Optional[str] = None
    MOA05_claim_payment_remark_code_3: Optional[str] = None
    MOA06_claim_payment_remark_code_4: Optional[str] = None
    MOA07_claim_payment_remark_code_5: Optional[str] = None
    MOA08_esrd_payment_amount: Optional[float] = None
    MOA09_professional_component_amount_billed_but_not_payable: Optional[float] = None

class X12_835_5010_X221A1_Detail_2100_NM1_V0(BaseModel):
    NM101_entity_identifier_code: Optional[str] = None
    NM102_entity_type_qualifier: Optional[str] = None
    NM103_name_last_or_organization_name: Optional[str] = None
    NM104_name_first: Optional[str] = None
    NM105_name_middle: Optional[str] = None
    NM106_name_prefix: Optional[str] = None
    NM107_name_suffix: Optional[str] = None
    NM108_identification_code_qualifier: Optional[str] = None
    NM109_identification_code: Optional[str] = None
    NM110_entity_relationship_code: Optional[str] = None
    NM111_additional_entity_identifier_code: Optional[str] = None
    NM112_secondary_name_last_or_organization_name: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_PER_V0(BaseModel):
    PER01_contact_function_code: Optional[str] = None
    PER02_name: Optional[str] = None
    PER03_communication_number_qualifier_1: Optional[str] = None
    PER04_communication_number_1: Optional[str] = None
    PER05_communication_number_qualifier_2: Optional[str] = None
    PER06_communication_number_2: Optional[str] = None
    PER07_communication_number_qualifier_3: Optional[str] = None
    PER08_communication_number_3: Optional[str] = None
    PER09_contact_inquiry_reference: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_QTY_C001_V0(BaseModel):
    C001_01_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_02_exponent: Optional[float] = None
    C001_03_multiplier: Optional[float] = None
    C001_04_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_05_exponent: Optional[float] = None
    C001_06_multiplier: Optional[float] = None
    C001_07_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_08_exponent: Optional[float] = None
    C001_09_multiplier: Optional[float] = None
    C001_10_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_11_exponent: Optional[float] = None
    C001_12_multiplier: Optional[float] = None
    C001_13_unit_or_basis_for_measurement_code: Optional[str] = None
    C001_14_exponent: Optional[float] = None
    C001_15_multiplier: Optional[float] = None

class X12_835_5010_X221A1_Detail_2100_QTY_V0(BaseModel):
    QTY01_quantity_qualifier: Optional[str] = None
    QTY02_quantity: Optional[float] = None
    QTY03_composite_unit_of_measure: Optional["X12_835_5010_X221A1_Detail_2100_QTY_C001_V0"] = None
    QTY04_free_form_information: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_REF_C040_V0(BaseModel):
    C040_01_reference_identification_qualifier: Optional[str] = None
    C040_02_reference_identification: Optional[str] = None
    C040_03_reference_identification_qualifier: Optional[str] = None
    C040_04_reference_identification: Optional[str] = None
    C040_05_reference_identification_qualifier: Optional[str] = None
    C040_06_reference_identification: Optional[str] = None

class X12_835_5010_X221A1_Detail_2100_REF_V0(BaseModel):
    REF01_reference_identification_qualifier: Optional[str] = None
    REF02_reference_identification: Optional[str] = None
    REF03_description: Optional[str] = None
    REF04_composite_reference_identifier: Optional["X12_835_5010_X221A1_Detail_2100_REF_C040_V0"] = None

class X12_835_5010_X221A1_Detail_LX_V0(BaseModel):
    LX01_assigned_number: Optional[int] = None

class X12_835_5010_X221A1_Detail_Loop_V0(BaseModel):
    LX_header_number: Optional["X12_835_5010_X221A1_Detail_LX_V0"] = None
    TS3_provider_summary_information: Optional["X12_835_5010_X221A1_Detail_TS3_V0"] = None
    TS2_provider_supplemental_summary_information: Optional["X12_835_5010_X221A1_Detail_TS2_V0"] = None
    claim_level_loop: List["X12_835_5010_X221A1_Detail_2100_Loop_V0"]

class X12_835_5010_X221A1_Detail_TS2_V0(BaseModel):
    TS201_total_drg_amount: Optional[float] = None
    TS202_total_federal_specific_amount: Optional[float] = None
    TS203_total_hospital_specific_amount: Optional[float] = None
    TS204_total_disproportionate_share_amount: Optional[float] = None
    TS205_total_capital_amount: Optional[float] = None
    TS206_total_indirect_medical_education_amount: Optional[float] = None
    TS207_total_outlier_days: Optional[float] = None
    TS208_total_day_outlier_amount: Optional[float] = None
    TS209_total_cost_outlier_amount: Optional[float] = None
    TS210_drg_average_length_of_stay: Optional[float] = None
    TS211_total_discharges: Optional[float] = None
    TS212_total_cost_report_days: Optional[float] = None
    TS213_total_covered_days: Optional[float] = None
    TS214_total_non_covered_days: Optional[float] = None
    TS215_total_msp_pass_through_amount: Optional[float] = None
    TS216_average_drg_weight: Optional[float] = None
    TS217_total_pps_capital_federal_specific_drg_amount: Optional[float] = None
    TS218_total_pps_capital_hospital_specific_drg_amount: Optional[float] = None
    TS219_total_pps_disproportionate_share_drg_amount: Optional[float] = None

class X12_835_5010_X221A1_Detail_TS3_V0(BaseModel):
    TS301_reference_identification: Optional[str] = None
    TS302_facility_code_value: Optional[str] = None
    TS303_date: Optional[str] = None
    TS304_quantity: Optional[float] = None
    TS305_total_reported_charges: Optional[float] = None
    TS306_total_covered_charges: Optional[float] = None
    TS307_total_noncovered_charges: Optional[float] = None
    TS308_total_denied_charges: Optional[float] = None
    TS309_total_provider_payment: Optional[float] = None
    TS310_total_interest_paid: Optional[float] = None
    TS311_total_contractual_adjustment: Optional[float] = None
    TS312_total_gramm_rudman_reduction: Optional[float] = None
    TS313_total_medicare_secondary_payer_primary_payer_amount: Optional[float] = None
    TS314_total_blood_deductible_amount: Optional[float] = None
    TS315_total_non_lab_charges: Optional[float] = None
    TS316_total_coinsurance_amount: Optional[float] = None
    TS317_hcpcs_reported_charges: Optional[float] = None
    TS318_hcpcs_payable_amount: Optional[float] = None
    TS319_total_deductible_amount: Optional[float] = None
    TS320_total_professional_component_amount: Optional[float] = None
    TS321_total_msp_patient_liability_met: Optional[float] = None
    TS322_total_patient_reimbursement: Optional[float] = None
    TS323_total_pip_number_of_claims: Optional[float] = None
    TS324_total_pip_adjustment: Optional[float] = None

class X12_835_5010_X221A1_Extractor_Input_V0(BaseModel):
    body: Optional[str] = None

class X12_835_5010_X221A1_Extractor_Output_V0(BaseModel):
    data: Optional["X12_835_5010_X221A1_Extractor_Schema_V0"] = None

class X12_835_5010_X221A1_Extractor_Schema_V0(BaseModel):
    heading: Optional["X12_835_5010_X221A1_Heading"] = None
    detail: List["X12_835_5010_X221A1_Detail_Loop_V0"]
    summary: Optional["X12_835_5010_X221A1_Summary_V0"] = None

class X12_835_5010_X221A1_Heading(BaseModel):
    ST_transaction_set_header: Optional["X12_835_5010_X221A1_Heading_ST_V0"] = None
    BPR_financial_information: Optional["X12_835_5010_X221A1_Heading_BPR_V0"] = None
    TRN_reassociation_trace_number: Optional["X12_835_5010_X221A1_Heading_TRN_V0"] = None
    CUR_currency: Optional["X12_835_5010_X221A1_Heading_CUR_V0"] = None
    REF_receiver_identification: Optional["X12_835_5010_X221A1_Heading_REF_V0"] = None
    REF_version_identification: Optional["X12_835_5010_X221A1_Heading_REF_V0"] = None
    DTM_production_date: Optional["X12_835_5010_X221A1_Heading_DTM_V0"] = None
    payer_identification_loop: List["X12_835_5010_X221A1_Heading_1000A_Loop_V0"]
    payee_identification_loop: List["X12_835_5010_X221A1_Heading_1000B_Loop_V0"]

class X12_835_5010_X221A1_Heading_1000A_Loop_V0(BaseModel):
    N1_payer_identification: Optional["X12_835_5010_X221A1_Heading_1000A_N1_V0"] = None
    N3_payer_address: Optional["X12_835_5010_X221A1_Heading_1000A_N3_V0"] = None
    N4_payer_city_state_zip_code: Optional["X12_835_5010_X221A1_Heading_1000A_N4_V0"] = None
    REF_additional_payer_identification: List["X12_835_5010_X221A1_Heading_1000A_REF_V0"]
    PER_payer_business_contact_information: Optional["X12_835_5010_X221A1_Heading_1000A_PER_V0"] = None
    PER_payer_technical_contact_information: List["X12_835_5010_X221A1_Heading_1000A_PER_V0"]
    PER_payer_web_site: Optional["X12_835_5010_X221A1_Heading_1000A_PER_V0"] = None

class X12_835_5010_X221A1_Heading_1000A_N1_V0(BaseModel):
    N101_entity_identifier_code: Optional[str] = None
    N102_name: Optional[str] = None
    N103_identification_code_qualifier: Optional[str] = None
    N104_identification_code: Optional[str] = None
    N105_entity_relationship_code: Optional[str] = None
    N106_entity_identifier_code: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000A_N3_V0(BaseModel):
    N301_address_information: Optional[str] = None
    N302_address_information: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000A_N4_V0(BaseModel):
    N401_city_name: Optional[str] = None
    N402_state_or_province_code: Optional[str] = None
    N403_postal_code: Optional[str] = None
    N404_country_code: Optional[str] = None
    N405_location_qualifier: Optional[str] = None
    N406_location_identifier: Optional[str] = None
    N407_country_subdivision_code: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000A_PER_V0(BaseModel):
    PER01_contact_function_code: Optional[str] = None
    PER02_name: Optional[str] = None
    PER03_communication_number_qualifier_1: Optional[str] = None
    PER04_communication_number_1: Optional[str] = None
    PER05_communication_number_qualifier_2: Optional[str] = None
    PER06_communication_number_2: Optional[str] = None
    PER07_communication_number_qualifier_3: Optional[str] = None
    PER08_communication_number_3: Optional[str] = None
    PER09_contact_inquiry_reference: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000A_REF_C040_V0(BaseModel):
    C040_01_reference_identification_qualifier: Optional[str] = None
    C040_02_reference_identification: Optional[str] = None
    C040_03_reference_identification_qualifier: Optional[str] = None
    C040_04_reference_identification: Optional[str] = None
    C040_05_reference_identification_qualifier: Optional[str] = None
    C040_06_reference_identification: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000A_REF_V0(BaseModel):
    REF01_reference_identification_qualifier: Optional[str] = None
    REF02_reference_identification: Optional[str] = None
    REF03_description: Optional[str] = None
    REF04_composite_reference_identifier: Optional["X12_835_5010_X221A1_Heading_1000A_REF_C040_V0"] = None

class X12_835_5010_X221A1_Heading_1000B_Loop_V0(BaseModel):
    N1_payee_identification: Optional["X12_835_5010_X221A1_Heading_1000B_N1_V0"] = None
    N3_payee_address: Optional["X12_835_5010_X221A1_Heading_1000B_N3_V0"] = None
    N4_payee_city_state_zip_code: Optional["X12_835_5010_X221A1_Heading_1000B_N4_V0"] = None
    REF_payee_additional_identification: List["X12_835_5010_X221A1_Heading_1000B_REF_V0"]
    RDM_remittance_delivery_method: Optional["X12_835_5010_X221A1_Heading_1000B_RDM_V0"] = None

class X12_835_5010_X221A1_Heading_1000B_N1_V0(BaseModel):
    N101_entity_identifier_code: Optional[str] = None
    N102_name: Optional[str] = None
    N103_identification_code_qualifier: Optional[str] = None
    N104_identification_code: Optional[str] = None
    N105_entity_relationship_code: Optional[str] = None
    N106_entity_identifier_code: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000B_N3_V0(BaseModel):
    N301_address_information: Optional[str] = None
    N302_address_information: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000B_N4_V0(BaseModel):
    N401_city_name: Optional[str] = None
    N402_state_or_province_code: Optional[str] = None
    N403_postal_code: Optional[str] = None
    N404_country_code: Optional[str] = None
    N405_location_qualifier: Optional[str] = None
    N406_location_identifier: Optional[str] = None
    N407_country_subdivision_code: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000B_RDM_C040_V0(BaseModel):
    C040_01_reference_identification_qualifier: Optional[str] = None
    C040_02_reference_identification: Optional[str] = None
    C040_03_reference_identification_qualifier: Optional[str] = None
    C040_04_reference_identification: Optional[str] = None
    C040_05_reference_identification_qualifier: Optional[str] = None
    C040_06_reference_identification: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000B_RDM_V0(BaseModel):
    RDM01_report_transmission_code: Optional[str] = None
    RDM02_name: Optional[str] = None
    RDM03_communication_number: Optional[str] = None
    RDM04_composite_reference_identifier: Optional["X12_835_5010_X221A1_Heading_1000B_RDM_C040_V0"] = None
    RDM05_composite_reference_identifier: Optional["X12_835_5010_X221A1_Heading_1000B_RDM_C040_V0"] = None

class X12_835_5010_X221A1_Heading_1000B_REF_C040_V0(BaseModel):
    C040_01_reference_identification_qualifier: Optional[str] = None
    C040_02_reference_identification: Optional[str] = None
    C040_03_reference_identification_qualifier: Optional[str] = None
    C040_04_reference_identification: Optional[str] = None
    C040_05_reference_identification_qualifier: Optional[str] = None
    C040_06_reference_identification: Optional[str] = None

class X12_835_5010_X221A1_Heading_1000B_REF_V0(BaseModel):
    REF01_reference_identification_qualifier: Optional[str] = None
    REF02_reference_identification: Optional[str] = None
    REF03_description: Optional[str] = None
    REF04_composite_reference_identifier: Optional["X12_835_5010_X221A1_Heading_1000B_REF_C040_V0"] = None

class X12_835_5010_X221A1_Heading_BPR_V0(BaseModel):
    BPR01_transaction_handling_code: Optional[str] = None
    BPR02_monetary_amount: Optional[float] = None
    BPR03_credit_debit_flag_code: Optional[str] = None
    BPR04_payment_method_code: Optional[str] = None
    BPR05_payment_format_code: Optional[str] = None
    BPR06_dfi_id_number_qualifier: Optional[str] = None
    BPR07_dfi_identification_number: Optional[str] = None
    BPR08_account_number_qualifier: Optional[str] = None
    BPR09_account_number: Optional[str] = None
    BPR10_originating_company_identifier: Optional[str] = None
    BPR11_originating_company_supplemental_code: Optional[str] = None
    BPR12_dfi_id_number_qualifier_receiver: Optional[str] = None
    BPR13_dfi_identification_number_receiver: Optional[str] = None
    BPR14_account_number_qualifier_receiver: Optional[str] = None
    BPR15_account_number_receiver: Optional[str] = None
    BPR16_date: Optional[str] = None
    BPR17_business_function_code: Optional[str] = None
    BPR18_dfi_id_number_qualifier_return: Optional[str] = None
    BPR19_dfi_identification_number_return: Optional[str] = None
    BPR20_account_number_qualifier_return: Optional[str] = None
    BPR21_account_number_return: Optional[str] = None

class X12_835_5010_X221A1_Heading_CUR_V0(BaseModel):
    CUR01_entity_identifier_code: Optional[str] = None
    CUR02_currency_code: Optional[str] = None
    CUR03_exchange_rate: Optional[float] = None
    CUR04_entity_identifier_code: Optional[str] = None
    CUR05_secondary_currency_code: Optional[str] = None
    CUR06_currency_market_exchange_code: Optional[str] = None
    CUR07_date_time_qualifier: Optional[str] = None
    CUR08_date: Optional[str] = None
    CUR09_time: Optional[str] = None
    CUR10_secondary_date_time_qualifier: Optional[str] = None
    CUR11_secondary_date: Optional[str] = None
    CUR12_secondary_time: Optional[str] = None
    CUR13_additional_date_time_qualifier: Optional[str] = None
    CUR14_additional_date: Optional[str] = None
    CUR15_additional_time: Optional[str] = None
    CUR16_final_date_time_qualifier: Optional[str] = None
    CUR17_final_date: Optional[str] = None
    CUR18_final_time: Optional[str] = None
    CUR19_last_date_time_qualifier: Optional[str] = None
    CUR20_last_date: Optional[str] = None
    CUR21_last_time: Optional[str] = None

class X12_835_5010_X221A1_Heading_DTM_V0(BaseModel):
    DTM01_date_time_qualifier: Optional[str] = None
    DTM02_date: Optional[str] = None
    DTM03_time: Optional[str] = None
    DTM04_time_code: Optional[str] = None
    DTM05_date_time_period_format_qualifier: Optional[str] = None
    DTM06_date_time_period: Optional[str] = None

class X12_835_5010_X221A1_Heading_REF_C040_V0(BaseModel):
    C040_01_reference_id_qualifier: Optional[str] = None
    C040_02_reference_id: Optional[str] = None
    C040_03_secondary_reference_id_qualifier: Optional[str] = None
    C040_04_secondary_reference_id: Optional[str] = None
    C040_05_tertiary_reference_id_qualifier: Optional[str] = None
    C040_06_tertiary_reference_id: Optional[str] = None

class X12_835_5010_X221A1_Heading_REF_V0(BaseModel):
    REF01_reference_id_qualifier: Optional[str] = None
    REF02_reference_id: Optional[str] = None
    REF03_description: Optional[str] = None
    REF04_composite_reference_identifier: Optional["X12_835_5010_X221A1_Heading_REF_C040_V0"] = None

class X12_835_5010_X221A1_Heading_ST_V0(BaseModel):
    ST01_transaction_set_identifier_code: Optional[str] = None
    ST02_transaction_set_control_number: Optional[str] = None
    ST03_implementation_convention_reference: Optional[str] = None

class X12_835_5010_X221A1_Heading_TRN_V0(BaseModel):
    TRN01_trace_type_code: Optional[str] = None
    TRN02_reference_identification: Optional[str] = None
    TRN03_originating_company_identifier: Optional[str] = None
    TRN04_reference_identification: Optional[str] = None

class X12_835_5010_X221A1_Judge_Input_V0(BaseModel):
    extraction: Optional["X12_835_5010_X221A1_Extractor_Output_V0"] = None

class X12_835_5010_X221A1_Judge_Output_V0(BaseModel):
    data: Optional["X12_835_5010_X221A1_Judge_Schema"] = None

class X12_835_5010_X221A1_Judge_Schema(BaseModel):
    status: Optional[Union[Literal["failed"], Literal["passed"]]] = None
    message: Optional[str] = None
    errors: List["X12_835_5010_X221A1_Judge_Schema_Error"]
    summary: Optional["X12_835_5010_X221A1_Judge_Schema_Summary"] = None

class X12_835_5010_X221A1_Judge_Schema_Error(BaseModel):
    extractor_id: Optional[str] = None
    segment: Optional[str] = None
    element: Optional[str] = None
    issue: Optional[str] = None
    description: Optional[str] = None

class X12_835_5010_X221A1_Judge_Schema_Summary(BaseModel):
    total_extractions: Optional[int] = None
    total_errors: Optional[int] = None
    extraction_status: Optional[Union[Literal["valid"], Literal["invalid"]]] = None

class X12_835_5010_X221A1_Summary_PLB_C042_V0(BaseModel):
    adjustment_reason_code: Optional[str] = None
    reference_identification: Optional[str] = None

class X12_835_5010_X221A1_Summary_PLB_V0(BaseModel):
    PLB01_provider_identifier: Optional[str] = None
    PLB02_fiscal_period_date: Optional[str] = None
    PLB03_adjustment_identifier: Optional["X12_835_5010_X221A1_Summary_PLB_C042_V0"] = None
    PLB04_adjustment_amount: Optional[float] = None
    PLB05_adjustment_identifier: Optional["X12_835_5010_X221A1_Summary_PLB_C042_V0"] = None
    PLB06_adjustment_amount: Optional[float] = None
    PLB07_adjustment_identifier: Optional["X12_835_5010_X221A1_Summary_PLB_C042_V0"] = None
    PLB08_adjustment_amount: Optional[float] = None
    PLB09_adjustment_identifier: Optional["X12_835_5010_X221A1_Summary_PLB_C042_V0"] = None
    PLB10_adjustment_amount: Optional[float] = None
    PLB11_adjustment_identifier: Optional["X12_835_5010_X221A1_Summary_PLB_C042_V0"] = None
    PLB12_adjustment_amount: Optional[float] = None
    PLB13_adjustment_identifier: Optional["X12_835_5010_X221A1_Summary_PLB_C042_V0"] = None
    PLB14_adjustment_amount: Optional[float] = None

class X12_835_5010_X221A1_Summary_SE_V0(BaseModel):
    SE01_number_of_included_segments: Optional[int] = None
    SE02_transaction_set_control_number: Optional[str] = None

class X12_835_5010_X221A1_Summary_V0(BaseModel):
    PLB_provider_adjustments: List["X12_835_5010_X221A1_Summary_PLB_V0"]
    SE_transaction_set_trailer: Optional["X12_835_5010_X221A1_Summary_SE_V0"] = None

class X12_835_5010_X221A1_Validator_Input_V0(BaseModel):
    body: Optional[str] = None

class X12_835_5010_X221A1_Validator_Output_V0(BaseModel):
    data: Optional["X12_835_5010_X221A1_Validator_Schema"] = None

class X12_835_5010_X221A1_Validator_Schema(BaseModel):
    status: Optional[Union[Literal["failed"], Literal["passed"]]] = None
    message: Optional[str] = None
    errors: List["X12_835_5010_X221A1_Validator_Schema_Errors"]

class X12_835_5010_X221A1_Validator_Schema_Errors(BaseModel):
    segment: Optional[str] = None
    element: Optional[str] = None
    issue: Optional[str] = None
    description: Optional[str] = None
