###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import typing
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder
from baml_py.type_builder import TypeBuilder as _TypeBuilder, ClassPropertyBuilder

class TypeBuilder(_TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["X12Input","X12Output","X12_835_5010","X12_835_5010_AMT_V0","X12_835_5010_BPR_V0","X12_835_5010_CAS_V0","X12_835_5010_CLP_V0","X12_835_5010_CUR_V0","X12_835_5010_DTM_V0","X12_835_5010_GE_V0","X12_835_5010_GS_V0","X12_835_5010_IEA_V0","X12_835_5010_ISA_V0","X12_835_5010_LX_V0","X12_835_5010_MOA_V0","X12_835_5010_N1_V0","X12_835_5010_N2_V0","X12_835_5010_N3_V0","X12_835_5010_N4_V0","X12_835_5010_NM1_V0","X12_835_5010_PER_V0","X12_835_5010_REF_V0","X12_835_5010_SE_V0","X12_835_5010_ST_V0","X12_835_5010_SVC_V0","X12_835_5010_TRN_V0",]
        ), enums=set(
          []
        ))









__all__ = ["TypeBuilder"]