class X12_835_5010_X221A1_Detail_2100_MOA_V0 { 
    MOA01_reimbursement_rate float?
    MOA02_hcpcs_payable_amount float?
    MOA03_claim_payment_remark_code_1 string?
    MOA04_claim_payment_remark_code_2 string?
    MOA05_claim_payment_remark_code_3 string?
    MOA06_claim_payment_remark_code_4 string?
    MOA07_claim_payment_remark_code_5 string?
    MOA08_esrd_payment_amount float?
    MOA09_professional_component_amount_billed_but_not_payable float?
}
