class X12_835_5010_X221A1_Detail_2100_MIA_V0 {  
    MIA01_covered_days float
    MIA02_pps_operating_outlier_amount float?
    MIA03_lifetime_psychiatric_days float?
    MIA04_drg_amount float?
    MIA05_claim_payment_remark_code string?
    MIA06_disproportionate_share_amount float?
    MIA07_msp_pass_through_amount float?
    MIA08_total_pps_capital_amount float?
    MIA09_pps_capital_federal_specific_drg_amount float?
    MIA10_pps_capital_hospital_specific_drg_amount float?
    MIA11_pps_capital_disproportionate_share_drg_amount float?
    MIA12_old_capital_amount float?
    MIA13_pps_capital_indirect_medical_education_claim_amount float?
    MIA14_hospital_specific_drg_amount float?
    MIA15_cost_report_days float?
    MIA16_federal_specific_drg_amount float?
    MIA17_pps_capital_outlier_amount float?
    MIA18_indirect_teaching_amount float?
    MIA19_professional_component_amount_billed_but_not_payable float?
    MIA20_claim_payment_remark_code_1 string?
    MIA21_claim_payment_remark_code_2 string?
    MIA22_claim_payment_remark_code_3 string?
    MIA23_claim_payment_remark_code_4 string?
    MIA24_capital_exception_amount float?
}
