class X12_835_5010_X221A1_Detail_2100_CAS_V0 { 
    CAS01_claim_adjustment_group_code string
    CAS02_reason_code string
    CAS03_adjustment_amount float
    CAS04_adjustment_quantity float?
    CAS05_reason_code string?
    CAS06_adjustment_amount float?
    CAS07_adjustment_quantity float?
    CAS08_reason_code string?
    CAS09_adjustment_amount float?
    CAS10_adjustment_quantity float?
    CAS11_reason_code string?
    CAS12_adjustment_amount float?
    CAS13_adjustment_quantity float?
    CAS14_reason_code string?
    CAS15_adjustment_amount float?
    CAS16_adjustment_quantity float?
    CAS17_reason_code string?
    CAS18_adjustment_amount float?
    CAS19_adjustment_quantity float?
}
