class X12_835_5010_X221A1_Detail_TS2_V0 { 
    TS201_total_drg_amount float?
    TS202_total_federal_specific_amount float?
    TS203_total_hospital_specific_amount float?
    TS204_total_disproportionate_share_amount float?
    TS205_total_capital_amount float?
    TS206_total_indirect_medical_education_amount float?
    TS207_total_outlier_days float?
    TS208_total_day_outlier_amount float?
    TS209_total_cost_outlier_amount float?
    TS210_drg_average_length_of_stay float?
    TS211_total_discharges float?
    TS212_total_cost_report_days float?
    TS213_total_covered_days float?
    TS214_total_non_covered_days float?
    TS215_total_msp_pass_through_amount float?
    TS216_average_drg_weight float?
    TS217_total_pps_capital_federal_specific_drg_amount float?
    TS218_total_pps_capital_hospital_specific_drg_amount float?
    TS219_total_pps_disproportionate_share_drg_amount float?
}
