class X12_835_5010_X221A1_Detail_TS3_V0 {  
    TS301_reference_identification string
    TS302_facility_code_value string
    TS303_date string
    TS304_quantity float
    TS305_total_reported_charges float
    TS306_total_covered_charges float?
    TS307_total_noncovered_charges float?
    TS308_total_denied_charges float?
    TS309_total_provider_payment float?
    TS310_total_interest_paid float?
    TS311_total_contractual_adjustment float?
    TS312_total_gramm_rudman_reduction float?
    TS313_total_medicare_secondary_payer_primary_payer_amount float?
    TS314_total_blood_deductible_amount float?
    TS315_total_non_lab_charges float?
    TS316_total_coinsurance_amount float?
    TS317_hcpcs_reported_charges float?
    TS318_hcpcs_payable_amount float?
    TS319_total_deductible_amount float?
    TS320_total_professional_component_amount float?
    TS321_total_msp_patient_liability_met float?
    TS322_total_patient_reimbursement float?
    TS323_total_pip_number_of_claims float?
    TS324_total_pip_adjustment float?
}
