class X12_835_5010_X221A1_Detail_2100_CLP_V0 {
    CLP01_claim_submitters_identifier string
    CLP02_claim_status_code string
    CLP03_submitted_charges_amount float
    CLP04_paid_amount float
    CLP05_patient_responsibility_amount float?
    CLP06_claim_filing_indicator_code string?
    CLP07_payer_control_number string?
    CLP08_facility_code_value string?
    CLP09_claim_frequency_type_code string?
    CLP10_patient_status_code string?
    CLP11_drg_code string?
    CLP12_drg_weight float?
    CLP13_discharge_fraction float?
    CLP14_patient_authorization_to_coordinate_benefits string?
}
