class X12_835_5010_X221A1_Heading_BPR_V0 {   
    BPR01_transaction_handling_code string
    BPR02_monetary_amount float
    BPR03_credit_debit_flag_code string
    BPR04_payment_method_code string
    BPR05_payment_format_code string?
    BPR06_dfi_id_number_qualifier string?
    BPR07_dfi_identification_number string?
    BPR08_account_number_qualifier string?
    BPR09_account_number string?
    BPR10_originating_company_identifier string?
    BPR11_originating_company_supplemental_code string?
    BPR12_dfi_id_number_qualifier_receiver string?
    BPR13_dfi_identification_number_receiver string?
    BPR14_account_number_qualifier_receiver string?
    BPR15_account_number_receiver string?
    BPR16_date string?
    BPR17_business_function_code string?
    BPR18_dfi_id_number_qualifier_return string?
    BPR19_dfi_identification_number_return string?
    BPR20_account_number_qualifier_return string?
    BPR21_account_number_return string?
}
