class X12_835_5010_X221A1_Detail_2100_2110_CAS_V0 {
    CAS01_claim_adjustment_group_code string
    CAS02_claim_adjustment_reason_code string
    CAS03_monetary_amount float
    CAS04_quantity float?
    CAS05_claim_adjustment_reason_code string?
    CAS06_monetary_amount float?
    CAS07_quantity float?
    CAS08_claim_adjustment_reason_code string?
    CAS09_monetary_amount float?
    CAS10_quantity float?
    CAS11_claim_adjustment_reason_code string?
    CAS12_monetary_amount float?
    CAS13_quantity float?
    CAS14_claim_adjustment_reason_code string?
    CAS15_monetary_amount float?
    CAS16_quantity float?
    CAS17_claim_adjustment_reason_code string?
    CAS18_monetary_amount float?
    CAS19_quantity float?
}
