class X12_835_5010_X221A1_Summary_PLB_V0 {  
    PLB01_provider_identifier string
    PLB02_fiscal_period_date string
    PLB03_adjustment_identifier X12_835_5010_X221A1_Summary_PLB_C042_V0
    PLB04_adjustment_amount float
    PLB05_adjustment_identifier X12_835_5010_X221A1_Summary_PLB_C042_V0?
    PLB06_adjustment_amount float?
    PLB07_adjustment_identifier X12_835_5010_X221A1_Summary_PLB_C042_V0?
    PLB08_adjustment_amount float?
    PLB09_adjustment_identifier X12_835_5010_X221A1_Summary_PLB_C042_V0?
    PLB10_adjustment_amount float?
    PLB11_adjustment_identifier X12_835_5010_X221A1_Summary_PLB_C042_V0?
    PLB12_adjustment_amount float?
    PLB13_adjustment_identifier X12_835_5010_X221A1_Summary_PLB_C042_V0?
    PLB14_adjustment_amount float?
}

class X12_835_5010_X221A1_Summary_PLB_C042_V0 {
    adjustment_reason_code string
    reference_identification string?
}

