class X12_835_5010_X221A1_Heading {   
    ST_transaction_set_header X12_835_5010_X221A1_Heading_ST_V0
    BPR_financial_information X12_835_5010_X221A1_Heading_BPR_V0
    TRN_reassociation_trace_number X12_835_5010_X221A1_Heading_TRN_V0?
    CUR_currency X12_835_5010_X221A1_Heading_CUR_V0?
    REF_receiver_identification X12_835_5010_X221A1_Heading_REF_V0?
    REF_version_identification X12_835_5010_X221A1_Heading_REF_V0?
    DTM_production_date X12_835_5010_X221A1_Heading_DTM_V0?
    payer_identification_loop X12_835_5010_X221A1_Heading_1000A_Loop_V0[]
    payee_identification_loop X12_835_5010_X221A1_Heading_1000B_Loop_V0[]
}
