class X12_835_5010_X221A1_Heading_1000B_RDM_V0 {   
    RDM01_report_transmission_code string
    RDM02_name string?
    RDM03_communication_number string?
    RDM04_composite_reference_identifier X12_835_5010_X221A1_Heading_1000B_RDM_C040_V0?
    RDM05_composite_reference_identifier X12_835_5010_X221A1_Heading_1000B_RDM_C040_V0?
}

class X12_835_5010_X221A1_Heading_1000B_RDM_C040_V0 { 
    C040_01_reference_identification_qualifier string
    C040_02_reference_identification string
    C040_03_reference_identification_qualifier string?
    C040_04_reference_identification string?
    C040_05_reference_identification_qualifier string?
    C040_06_reference_identification string?
}
