class X12_835_5010_X221A1_Detail_2100_NM1_V0 {
    NM101_entity_identifier_code string
    NM102_entity_type_qualifier string
    NM103_name_last_or_organization_name string?
    NM104_name_first string?
    NM105_name_middle string?
    NM106_name_prefix string?
    NM107_name_suffix string?
    NM108_identification_code_qualifier string?
    NM109_identification_code string?
    NM110_entity_relationship_code string?
    NM111_additional_entity_identifier_code string?
    NM112_secondary_name_last_or_organization_name string?
}
