class X12_835_5010_X221A1_Heading_CUR_V0 {  
    CUR01_entity_identifier_code string
    CUR02_currency_code string
    CUR03_exchange_rate float?
    CUR04_entity_identifier_code string?
    CUR05_secondary_currency_code string?
    CUR06_currency_market_exchange_code string?
    CUR07_date_time_qualifier string?
    CUR08_date string?
    CUR09_time string?
    CUR10_secondary_date_time_qualifier string?
    CUR11_secondary_date string?
    CUR12_secondary_time string?
    CUR13_additional_date_time_qualifier string?
    CUR14_additional_date string?
    CUR15_additional_time string?
    CUR16_final_date_time_qualifier string?
    CUR17_final_date string?
    CUR18_final_time string?
    CUR19_last_date_time_qualifier string?
    CUR20_last_date string?
    CUR21_last_time string?
}
