class X12_835_5010_X221A1_Heading_1000A_PER_V0 {
    PER01_contact_function_code string
    PER02_name string?
    PER03_communication_number_qualifier_1 string?
    PER04_communication_number_1 string?
    PER05_communication_number_qualifier_2 string?
    PER06_communication_number_2 string?
    PER07_communication_number_qualifier_3 string?
    PER08_communication_number_3 string?
    PER09_contact_inquiry_reference string?
}
